### ISSUE TITLE
Briefing RedirectionURL not found

### ISSUE THREAD

**Issue by marconline** [andrewfitz/alexa-fb#2]
Hello and thanks for this plugin.
It works ok but the redirectionURL generated doesn't point to a working page but to a page that gives "Oops! That page can't be found.  - It looks like nothing was found at this location. Maybe try onece again with a search?"

Would that be possible to give, as redirectionURL, a Wordpress post URL?

**Comment by andrewfitz** [comment]
The URL should go to the briefing post. Can you share your feed to take a look at? Also what version are you using? Master branch is latest as mirrored on WordPress.org 1.6

**Comment by marconline** [comment]
There you go: https://www.machine-learning.it/wp-json/alexa-fb/v1/briefings/?limit=5&cache=0

Thanks 👍

**Comment by marconline** [comment]
Hi, I'm using version 1.6. Wordpress version is 5.1.1.
PHP version is 7.2

**Comment by andrewfitz** [comment]
Do you have anything going on with permalink or cache? https://www.machine-learning.it/briefing/ Doesn’t work either, it should show all the briefings.

**Comment by marconline** [comment]
I don't know... How can I check?

**Comment by marconline** [comment]
Hi, I checked my Permalinks config and I restored back the basic config and it started to work.

**Comment by andrewfitz** [comment]
Great to hear, thanks for the update.

**Comment by marconline** [comment]
No, Sorry. Now the feed doesn't work. Can you please check?

**Comment by marconline** [comment]
The problem was in the settings of Permalinks. I had to set "blog post" as Permalink type.
